aliyun-dataworks-mcp-server:
  default:
    rootPath: ./
    languages:
      - nodejs20
    cache:
      paths:
        - "~/.cache"
    steps:
      - run: npm install alibabacloud-dataworks-mcp-server