aliyun-rds-mcp-server:
  default:
    rootPath: .
    languages:
      - python3.12
    cache:
      paths:
        - "~/.cache"
    steps:
      - run: mkdir -p python
      - run: pip install alibabacloud-rds-openapi-mcp-server -t python
      - run: find ./python/bin -type f -perm -u+x -exec sed -i '1{/^#!.*/ s|.*|#!/usr/bin/env python3|}' {} \;